export const REQUEST_USERS = 'REQUEST_USERS';
export const RECEIVE_USERS = 'RECEIVE_USERS';
export const CREATED_USER = 'CREATE_USER';

export const REQUEST_DEPTS = 'REQUEST_USERS';
export const RECEIVE_DEPTS = 'RECEIVE_USERS';
export const CREATED_DEPT = 'CREATE_USER';


